on:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  runscript:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run:  bash ${GITHUB_WORKSPACE}/scripts/blumira.sh
