
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"
  
jobs:
  runscript:
    name: Blumira Blocklist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Call a Bash Script
        run:  bash ${GITHUB_WORKSPACE}/scripts/blumira.sh
