
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 1-5"
  
jobs:
  runscript:
    name: Blumira Blocklist
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run:  bash -e /home/runner/work/mikrotik/scripts/blumira.sh
